import type { ProjectMetadata } from './types';

/**
 * ParserService — extrae los metadatos de impresión de un archivo G-code.
 *
 * La lectura es parcial a propósito: los slicers escriben todos los metadatos en
 * los primeros kilobytes del archivo (Cura los emite justo después de la línea
 * de Genius), así que no hay motivo para traerse un G-code de 200 MB a memoria.
 *
 * TODO: el parseo sigue devolviendo datos simulados. Cuando implemente el
 * parseo real habrá que detectar el slicer (Cura, PrusaSlicer, BambuStudio...)
 * y mapear sus comentarios de cabecera a `ProjectMetadata`.
 */

/** Extensiones que este servicio sabe interpretar. */
const GCODE_EXTENSIONS = ['.gcode', '.gco'] as const;

/**
 * Tamaño de la ventana de lectura inicial, en bytes.
 *
 * 256 KiB es un margen muy holgado: las cabeceras reales ocupan entre 1 y
 * 10 KiB. Bajarlo afinaría la lectura, pero cualquier slicer futuro con más
 * metadatos (perfiles, datos deodo, notas de usuario) se quedaría fuera.
 */
const HEADER_BYTES = 256 * 1024;

/** Latencia simulada para que los estados de carga de la UI sean visibles. */
const MOCK_LATENCY_MS = 400;

/** Resuelve tras `ms` milisegundos. Sustituye al trabajo real de lectura. */
const wait = (ms: number): Promise<void> =>
  new Promise((resolve) => {
    setTimeout(resolve, ms);
  });

/**
 * Lee únicamente la cabecera de un archivo G-code.
 *
 * Se usa `file.slice()` en lugar de `file.text()` porque `text()` trae el
 * archivo entero a memoria de una sentada: en un G-code de 200 MB eso significa
 * 200 MB de string en el hilo principal más el coste de decodificarlo, y la
 * interfaz se congela mientras ocurre. `slice()` es perezoso —no lee nada del
 * disco hasta que se consume— y `Blob.text()` decodifica solo ese trozo, así
 * que el trabajo real se limita a unos cientos de kilobytes.
 *
 * Decodificación: siempre UTF-8, sin intentar detectar Latin-1. Es una decisión
 * consciente y no un descuido. Todas las claves de los tres slicers son ASCII
 * (temperaturas, alturas, tiempos, flags), así que esos valores nunca se ven
 * afectados. El único campo con riesgo real es el material, cuyo nombre puede
 * llevar acentos; por eso el extractor lo sanea antes de usarlo en vez de
 * confiar en la decodificación.
 *
 * @param file Archivo `.gcode` / `.gco` seleccionado por el usuario.
 * @returns El texto de los primeros {@link HEADER_BYTES} del archivo.
 */
export async function readGcodeHeader(file: File): Promise<string> {
  return file.slice(0, HEADER_BYTES).text();
}

/** Slicers cuyas cabeceras se saben interpretar. */
export type SlicerKind = 'cura' | 'prusa' | 'orca' | 'unknown';

/**
 * Señal de detección: un comentario que solo escribe un slicer concreto.
 *
 * Cada señal lleva la razón por la que es discriminante, porque estas regex son
 * el punto donde este servicio se vuelve frágil: una clave demasiado genérica
 * (`; temperature = ...`) aparece en dos de los tres formatos y detectaría el
 * slicer equivocado.
 */
interface SlicerSignal {
  /** Patrón evaluado sobre la cabecera completa, con flags `mi`. */
  pattern: RegExp;
  /** Por qué este comentario identifica al slicer sin ambigüedad. */
  why: string;
}

/**
 * Señales de Cura, en orden de fiabilidad.
 *
 * Cura es el más fácil de identificar porque escribe comentarios en mayúsculas
 * separados por dos puntos (`;TIME:3600`), un estilo que Prusa y Orca no usan:
 * ellos escriben pares `clave = valor` en minúscula.
 */
const CURA_SIGNALS: readonly SlicerSignal[] = [
  {
    // La firma de versión es la señal más fuerte: solo Cura la escribe.
    pattern: /^;\s*Generated with Cura_SteamEngine\s+\S+/im,
    why: 'línea de firma de versión que solo emite CuraEngine',
  },
  {
    pattern: /^;\s*FLAVOR:\s*\S+/im,
    why: '`;FLAVOR:` es una directiva propia del gestor de perfiles de Cura',
  },
  {
    pattern: /^;\s*TIME:\s*\d+\s*$/im,
    why: 'clave `TIME:` en mayúsculas y sin espacios, estilo exclusivo de Cura',
  },
];

/**
 * Señales de PrusaSlicer / SuperSlicer.
 *
 * SuperSlicer es un fork de PrusaSlicer y conserva la cabecera tal cual, así que
 * comparten tabla en la Fase 3.
 */
const PRUSA_SIGNALS: readonly SlicerSignal[] = [
  {
    pattern: /^;\s*generated by PrusaSlicer\b/im,
    why: 'línea de firma que PrusaSlicer escribe en su G-code',
  },
  {
    pattern: /^;\s*generated by SuperSlicer\b/im,
    why: 'SuperSlicer es un fork de PrusaSlicer y firma con su propio nombre',
  },
  {
    // Prusa rotula el gramo como "used"; Orca usa "weight" (ver más abajo).
    pattern: /^;\s*total filament used \[g\]\s*=\s*\S/im,
    why: 'clave `total filament used [g]`, rotulación propia de PrusaSlicer',
  },
  {
    pattern: /^;\s*estimated printing time \(/im,
    why: 'parátesis en `estimated printing time (...)`, que Orca no escribe',
  },
];

/**
 * Señales de OrcaSlicer / BambuStudio.
 *
 * BambuStudio es un fork de OrcaSlicer y comparte cabecera, con la salvedad de
 * que Orca también emite claves de familia Prusa: el orden de las fases 2 y 3
 * tiene que respetar eso para no clasificarlos al revés.
 */
const ORCA_SIGNALS: readonly SlicerSignal[] = [
  {
    pattern: /^;\s*generated by OrcaSlicer\b/im,
    why: 'línea de firma que OrcaSlicer escribe en su G-code',
  },
  {
    pattern: /^;\s*generated by BambuStudio\b/im,
    why: 'BambuStudio es un fork de OrcaSlicer y firma con su propio nombre',
  },
  {
    // "weight" frente al "used" de Prusa: es el rasgo que los separa de verdad.
    pattern: /^;\s*total filament weight \[g\]\s*=\s*\S/im,
    why: 'clave `total filament weight [g]`, rotulación propia de OrcaSlicer',
  },
];

/**
 * Tablas de señales por slicer, indexadas por nombre.
 *
 * El `Record` es exhaustivo a propósito: añadir un slicer nuevo obliga a
 * declarar aquí su tabla de señales, que es justo lo que conviene no dejar para
 * más tarde.
 */
const SIGNALS_BY_SLICER: Record<Exclude<SlicerKind, 'unknown'>, readonly SlicerSignal[]> = {
  cura: CURA_SIGNALS,
  orca: ORCA_SIGNALS,
  prusa: PRUSA_SIGNALS,
};

/**
 * Orden en que se consultan las tablas de señales. Lista explícita, no el
 * orden de inserción de un objeto, porque la precedencia es una decisión de
 * diseño y no un accidente de iteración.
 *
 * El orden importa: Orca deriva de Prusa y escribe también claves de familia
 * Prusa (`nozzle_temperature`, `filament_type`), así que un archivo de Orca
 * cumpliría las señales débiles de Prusa. Por eso Orca se consulta antes: su
 * firma de versión y su clave `weight` son las que de verdad lo delatan, y una
 * vez que han fallado ya no hay mucho más que confundir.
 */
const DETECTION_ORDER: readonly Exclude<SlicerKind, 'unknown'>[] = ['cura', 'orca', 'prusa'];

/**
 * Identifica qué slicer generó el G-code a partir de su cabecera.
 *
 * Se detecta primero y la tabla correspondiente se aplica después, en lugar de
 * lanzar las tres a la vez: mezcladas, un archivo de Orca con
 * `nozzle_temperature` se interpretaría con las reglas de Prusa y su
 * `filament_type` acabaría leído con una convención que no es la suya.
 *
 * @param header Cabecera devuelta por {@link readGcodeHeader}.
 * @returns El slicer detectado, o `'unknown'` si no aparece ninguna señal fiable.
 */
export function detectSlicer(header: string): SlicerKind {
  for (const kind of DETECTION_ORDER) {
    const matched = SIGNALS_BY_SLICER[kind].some((signal) => signal.pattern.test(header));
    if (matched) return kind;
  }
  return 'unknown';
}

/**
 * Extrae los metadatos de impresión de un archivo G-code.
 *
 * @param file Archivo `.gcode` / `.gco` seleccionado por el usuario.
 * @throws {Error} Si la extensión no corresponde a un G-code.
 */
export async function parseGcode(file: File): Promise<ProjectMetadata> {
  const isGcode = GCODE_EXTENSIONS.some((ext) =>
    file.name.toLowerCase().endsWith(ext)
  );
  if (!isGcode) {
    throw new Error(`"${file.name}" no es un archivo G-code válido.`);
  }

  await wait(MOCK_LATENCY_MS);

  return buildMockMetadata(file.name);
}

/**
 * Genera metadatos de prueba deterministas a partir del nombre del archivo,
 * para que cada demo del panel de análisis reaccione de forma distinta.
 * Se sustituirá por el parseo real de la cabecera G-code.
 */
function buildMockMetadata(filename: string): ProjectMetadata {
  const seed = hashFilename(filename);
  const materials = ['PLA', 'PETG', 'ABS', 'ASA'] as const;
  const layerHeights = [0.1, 0.15, 0.2, 0.28] as const;

  return {
    filename,
    material: pick(materials, seed),
    hotendTemp: 200 + (seed % 3) * 10,
    bedTemp: 50 + (seed % 4) * 5,
    layerHeight: pick(layerHeights, seed),
    printTime: 5400 + (seed % 5) * 1800,
    filamentUsed: 32 + (seed % 6) * 9,
    hasOverhangs: seed % 3 !== 0,
    overhangAngle: 30 + (seed % 4) * 15,
  };
}

/** Elige un valor de la lista de forma determinista a partir de la semilla. */
function pick<T>(values: readonly T[], seed: number): T {
  const value = values[seed % values.length];
  if (value === undefined) {
    throw new Error('pick() espera una lista de valores no vacía.');
  }
  return value;
}

/** Hash entero simple y estable para derivar valores de la semilla. */
function hashFilename(filename: string): number {
  let hash = 0;
  for (let i = 0; i < filename.length; i++) {
    hash = (hash + filename.charCodeAt(i)) % 1000;
  }
  return hash;
}